//#region - LOADING
export const SHOW_LOADING = "SHOW_LOADING";
//#endregion

//#region - TOAST (global)
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
//#endregion

//#region - GENERICS
export const SUCCESS_GET_LOCALITIES = "SUCCESS_GET_LOCALITIES";
export const GET_LOCALITIES = "GET_LOCALITIES";

export const ERROR_LOCALITIES = "ERROR_LOCALITIES";
//#endregion

//#region - USER
export const SUCCESS_POST_LOGIN = "SUCCESS_POST_LOGIN";
export const POST_LOGIN = "POST_LOGIN";

export const CLEAR_LOGIN = "CLEAR_LOGIN"
export const ERROR_LOGIN = "ERROR_LOGIN"
//#endregion

//#region - VOLUNTEER
export const SUCCESS_POST_VOLUNTEER = "SUCCESS_POST_VOLUNTEER";
export const POST_VOLUNTEER = "POST_VOLUNTEER";

export const SUCCESS_POST_ASSISTANCE = "SUCCESS_POST_ASSISTANCE";
export const POST_ASSISTANCE = "POST_ASSISTANCE";

export const SUCCESS_GET_VOLUNTEERS_FREE = "SUCCESS_GET_VOLUNTEERS_FREE";
export const GET_VOLUNTEERS_FREE = "GET_VOLUNTEERS_FREE";

export const SUCCESS_GET_ASSISTANCE = "SUCCESS_GET_ASSISTANCE";
export const GET_ASSISTANCE = "GET_ASSISTANCE";

export const SUCCESS_GET_VOLUNTEERS_STATES = "SUCCESS_GET_VOLUNTEERS_STATES";
export const GET_VOLUNTEERS_STATES = "GET_VOLUNTEERS_STATES";

export const SUCCESS_GET_VOLUNTEER_BY_ID = "SUCCESS_GET_VOLUNTEER_BY_ID";
export const GET_VOLUNTEER_BY_ID = "GET_VOLUNTEER_BY_ID";

export const SUCCESS_PUT_VOLUNTEER = "SUCCESS_PUT_VOLUNTEER";
export const PUT_VOLUNTEER = "PUT_VOLUNTEER";

export const SUCCESS_GET_VOLUNTEERS = "SUCCESS_GET_VOLUNTEERS";
export const GET_VOLUNTEERS = "GET_VOLUNTEERS";

export const ERROR_VOLUNTEER = "ERROR_VOLUNTEER"

export const CLEAR_VOLUNTEER = "CLEAR_VOLUNTEER"
//#endregion

//#region - MOTHER
export const SUCCESS_POST_MOTHER = "SUCCESS_POST_MOTHER";
export const POST_MOTHER = "POST_MOTHER";

export const SUCCESS_GET_MOTHER = "SUCCESS_GET_MOTHER";
export const GET_MOTHER = "GET_MOTHER";

export const SUCCESS_GET_MOTHER_ID = "SUCCESS_GET_MOTHER_ID";
export const GET_MOTHER_ID = "GET_MOTHER_ID";

export const SUCCESS_GET_STATISTICS_LOCALITIES = "SUCCESS_GET_STATISTICS_LOCALITIES";
export const GET_STATISTICS_LOCALITIES = "GET_STATISTICS_LOCALITIES";

export const SUCCESS_GET_STATISTICS_AGE_MOTHER = "SUCCESS_GET_STATISTICS_AGE_MOTHER";
export const GET_STATISTICS_AGE_MOTHER = "GET_STATISTICS_AGE_MOTHER";

export const ERROR_MOTHER = "ERROR_MOTHER"
export const CLEAR_MOTHER = "CLEAR_MOTHER"

export const SUCCESS_PUT_MOTHER = "SUCCESS_PUT_MOTHER";
export const PUT_MOTHER = "PUT_MOTHER";

//#endregion

//#region - BABY
export const GET_BABYS = "GET_BABYS";
export const SUCCESS_GET_BABYS = "SUCCESS_GET_BABYS";
export const SUCCESS_POST_BABY = "SUCCESS_POST_BABY";
export const POST_BABY = "POST_BABY";

export const SUCCESS_GET_BABYS_FREE = "SUCCESS_GET_BABYS_FREE";
export const GET_BABYS_FREE = "GET_BABYS_FREE";

export const ERROR_BABY = "ERROR_BABY"
export const CLEAR_BABY = "CLEAR_BABY"
//#endregion

//#region - ASSIGNMENT
export const SUCCESS_POST_ASSIGNMENT_GENERATE = "SUCCESS_POST_ASSIGNMENT_GENERATE";
export const POST_ASSIGNMENT_GENERATE = "POST_ASSIGNMENT_GENERATE";

export const SUCCESS_POST_DETAIL_ASSIGNMENT = "SUCCESS_POST_DETAIL_ASSIGNMENT";
export const POST_DETAIL_ASSIGNMENT = "POST_DETAIL_ASSIGNMENT";

export const SUCCESS_POST_START_HUG = "SUCCESS_POST_START_HUG";
export const POST_START_HUG = "POST_START_HUG";

export const SUCCESS_POST_END_HUG = "SUCCESS_POST_END_HUG";
export const POST_END_HUG = "POST_END_HUG";

export const SUCCESS_GET_DURATION_HUG = "SUCCESS_GET_DURATION_HUG";
export const GET_DURATION_HUG = "GET_DURATION_HUG";

export const SUCCESS_GET_ASSIGNMENT_TODAY = "SUCCESS_GET_ASSIGNMENT_TODAY";
export const GET_ASSIGNMENT_TODAY = "GET_ASSIGNMENT_TODAY";

export const SUCCESS_GET_ASSIGNMENT_TODAY_BY_ID = "SUCCESS_GET_ASSIGNMENT_TODAY_BY_ID";
export const GET_ASSIGNMENT_TODAY_BY_ID = "GET_ASSIGNMENT_TODAY_BY_ID";

export const SUCCESS_GET_STATISTICS_ASSIGNMENT_MONTH = "SUCCESS_GET_STATISTICS_ASSIGNMENT_MONTH";
export const GET_STATISTICS_ASSIGNMENT_MONTH = "GET_STATISTICS_ASSIGNMENT_MONTH";

export const ERROR_ASSIGNMENT = "ERROR_ASSIGNMENT";
export const CLEAR_ASSIGNMENT = "CLEAR_ASSIGNMENT";
//#endregion

//#region - SUPPLY
export const SUCCESS_GET_SUPPLIES = "SUCCESS_GET_SUPPLIES";
export const GET_SUPPLIES = "GET_SUPPLIES";

export const SUCCESS_GET_STATISTICS_SUPPLIES = "SUCCESS_GET_STATISTICS_SUPPLIES";
export const GET_STATISTICS_SUPPLIES = "GET_STATISTICS_SUPPLIES";

export const ERROR_SUPPLY = "ERROR_SUPPLY";
export const CLEAR_SUPPLY = "CLEAR_SUPPLY";
//#endregion