//#region - LOADING
export const SHOW_LOADING = "SHOW_LOADING";
//#endregion

//#region - TOAST (global)
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
//#endregion

//#region - GENERICS
export const SUCCESS_GET_LOCALITIES = "SUCCESS_GET_LOCALITIES";
export const GET_LOCALITIES = "GET_LOCALITIES";
export const ERROR_LOCALITIES = "ERROR_LOCALITIES";

export const GET_ESTADOS_CIVILES = "GET_ESTADOS_CIVILES";
export const SUCCESS_GET_ESTADOS_CIVILES = "SUCCESS_GET_ESTADOS_CIVILES";
export const ERROR_ESTADOS_CIVILES = "ERROR_ESTADOS_CIVILES";
//#endregion

//#region - USER
export const SUCCESS_POST_LOGIN = "SUCCESS_POST_LOGIN";
export const POST_LOGIN = "POST_LOGIN";

export const CLEAR_LOGIN = "CLEAR_LOGIN"
export const ERROR_LOGIN = "ERROR_LOGIN"
//#endregion

//#region - VOLUNTEER
export const SUCCESS_POST_VOLUNTEER = "SUCCESS_POST_VOLUNTEER";
export const POST_VOLUNTEER = "POST_VOLUNTEER";

export const SUCCESS_POST_ASSISTANCE = "SUCCESS_POST_ASSISTANCE";
export const POST_ASSISTANCE = "POST_ASSISTANCE";

export const SUCCESS_POST_ASSISTANCE_SALIDA = "SUCCESS_POST_ASSISTANCE_SALIDA";
export const POST_ASSISTANCE_SALIDA = "POST_ASSISTANCE_SALIDA";

export const SUCCESS_GET_ASSISTANCE_TODAY = "SUCCESS_GET_ASSISTANCE_TODAY";
export const GET_ASSISTANCE_TODAY = "GET_ASSISTANCE_TODAY";

export const SUCCESS_GET_ASSISTANCE_HISTORICAS = "SUCCESS_GET_ASSISTANCE_HISTORICAS";
export const GET_ASSISTANCE_HISTORICAS = "GET_ASSISTANCE_HISTORICAS";

export const SUCCESS_GET_VOLUNTEERS_FREE = "SUCCESS_GET_VOLUNTEERS_FREE";
export const GET_VOLUNTEERS_FREE = "GET_VOLUNTEERS_FREE";

export const SUCCESS_GET_ASSISTANCE = "SUCCESS_GET_ASSISTANCE";
export const GET_ASSISTANCE = "GET_ASSISTANCE";

export const SUCCESS_GET_VOLUNTEERS_STATES = "SUCCESS_GET_VOLUNTEERS_STATES";
export const GET_VOLUNTEERS_STATES = "GET_VOLUNTEERS_STATES";

export const SUCCESS_GET_VOLUNTEER_BY_ID = "SUCCESS_GET_VOLUNTEER_BY_ID";
export const GET_VOLUNTEER_BY_ID = "GET_VOLUNTEER_BY_ID";

export const SUCCESS_PUT_VOLUNTEER = "SUCCESS_PUT_VOLUNTEER";
export const PUT_VOLUNTEER = "PUT_VOLUNTEER";

export const SUCCESS_GET_VOLUNTEERS = "SUCCESS_GET_VOLUNTEERS";
export const GET_VOLUNTEERS = "GET_VOLUNTEERS";

export const ERROR_VOLUNTEER = "ERROR_VOLUNTEER"

export const CLEAR_VOLUNTEER = "CLEAR_VOLUNTEER"
/** Conserva listados y datos de sesión; solo anula bajas asistencia/voluntaria y error. */
export const CLEAR_VOLUNTEER_WRITES = "CLEAR_VOLUNTEER_WRITES";
//#endregion

//#region - MOTHER
export const SUCCESS_POST_MOTHER = "SUCCESS_POST_MOTHER";
export const POST_MOTHER = "POST_MOTHER";

export const SUCCESS_GET_MOTHER = "SUCCESS_GET_MOTHER";
export const GET_MOTHER = "GET_MOTHER";

export const SUCCESS_GET_MOTHER_ID = "SUCCESS_GET_MOTHER_ID";
export const GET_MOTHER_ID = "GET_MOTHER_ID";

export const SUCCESS_GET_STATISTICS_LOCALITIES = "SUCCESS_GET_STATISTICS_LOCALITIES";
export const GET_STATISTICS_LOCALITIES = "GET_STATISTICS_LOCALITIES";

export const SUCCESS_GET_STATISTICS_AGE_MOTHER = "SUCCESS_GET_STATISTICS_AGE_MOTHER";
export const GET_STATISTICS_AGE_MOTHER = "GET_STATISTICS_AGE_MOTHER";

export const ERROR_MOTHER = "ERROR_MOTHER"
export const CLEAR_MOTHER = "CLEAR_MOTHER"
/** Limpia solo resultados de escritura (POST/PUT/delete); conserva `getMother` y `getMotherId` para listados y duplicados DNI. */
export const CLEAR_MOTHER_WRITES = "CLEAR_MOTHER_WRITES";
export const CLEAR_MOTHER_API_ERROR = "CLEAR_MOTHER_API_ERROR"

export const SUCCESS_PUT_MOTHER = "SUCCESS_PUT_MOTHER";
export const PUT_MOTHER = "PUT_MOTHER";

//#endregion

//#region - BABY
export const GET_BABYS = "GET_BABYS";
export const SUCCESS_GET_BABYS = "SUCCESS_GET_BABYS";
export const SUCCESS_POST_BABY = "SUCCESS_POST_BABY";
export const POST_BABY = "POST_BABY";

export const SUCCESS_GET_BABYS_FREE = "SUCCESS_GET_BABYS_FREE";
export const GET_BABYS_FREE = "GET_BABYS_FREE";

export const SUCCESS_PUT_BABY = "SUCCESS_PUT_BABY";
export const PUT_BABY = "PUT_BABY";

export const SUCCESS_GET_BABY_SALAS = "SUCCESS_GET_BABY_SALAS";
export const GET_BABY_SALAS = "GET_BABY_SALAS";

export const ERROR_BABY = "ERROR_BABY"
export const CLEAR_BABY = "CLEAR_BABY"
/** Solo flags de baja/edición reciente; conserva `getBabys`, `getBabyByDni`, etc. */
export const CLEAR_BABY_WRITES = "CLEAR_BABY_WRITES";
//#endregion

//#region - ASSIGNMENT
export const SUCCESS_POST_ASSIGNMENT_GENERATE = "SUCCESS_POST_ASSIGNMENT_GENERATE";
export const POST_ASSIGNMENT_GENERATE = "POST_ASSIGNMENT_GENERATE";

export const SUCCESS_POST_ASSIGNMENT_GENERATE_TAREA = "SUCCESS_POST_ASSIGNMENT_GENERATE_TAREA";
export const POST_ASSIGNMENT_GENERATE_TAREA = "POST_ASSIGNMENT_GENERATE_TAREA";

export const SUCCESS_GET_ASSIGNMENT_BY_ID = "SUCCESS_GET_ASSIGNMENT_BY_ID";
export const GET_ASSIGNMENT_BY_ID = "GET_ASSIGNMENT_BY_ID";

export const SUCCESS_POST_DETAIL_ASSIGNMENT = "SUCCESS_POST_DETAIL_ASSIGNMENT";
export const POST_DETAIL_ASSIGNMENT = "POST_DETAIL_ASSIGNMENT";

export const SUCCESS_POST_START_HUG = "SUCCESS_POST_START_HUG";
export const POST_START_HUG = "POST_START_HUG";

export const SUCCESS_POST_END_HUG = "SUCCESS_POST_END_HUG";
export const POST_END_HUG = "POST_END_HUG";


export const SUCCESS_GET_ASSIGNMENT_TODAY = "SUCCESS_GET_ASSIGNMENT_TODAY";
export const GET_ASSIGNMENT_TODAY = "GET_ASSIGNMENT_TODAY";

export const SUCCESS_GET_ASSIGNMENT_TODAY_BY_ID = "SUCCESS_GET_ASSIGNMENT_TODAY_BY_ID";
export const GET_ASSIGNMENT_TODAY_BY_ID = "GET_ASSIGNMENT_TODAY_BY_ID";

export const SUCCESS_GET_STATISTICS_ASSIGNMENT_MONTH = "SUCCESS_GET_STATISTICS_ASSIGNMENT_MONTH";
export const GET_STATISTICS_ASSIGNMENT_MONTH = "GET_STATISTICS_ASSIGNMENT_MONTH";

export const ERROR_ASSIGNMENT = "ERROR_ASSIGNMENT";
export const CLEAR_ASSIGNMENT = "CLEAR_ASSIGNMENT";
/** Anula solo PUT/DELETE/reset recientes; conserva consultas y listados del día en Tareas. */
export const CLEAR_ASSIGNMENT_WRITES = "CLEAR_ASSIGNMENT_WRITES";
//#endregion

//#region - SUPPLY
export const SUCCESS_GET_SUPPLIES = "SUCCESS_GET_SUPPLIES";
export const GET_SUPPLIES = "GET_SUPPLIES";

export const SUCCESS_GET_STATISTICS_SUPPLIES = "SUCCESS_GET_STATISTICS_SUPPLIES";
export const GET_STATISTICS_SUPPLIES = "GET_STATISTICS_SUPPLIES";

export const SUCCESS_POST_SUPPLY_CONSULT_MOVEMENTS = "SUCCESS_POST_SUPPLY_CONSULT_MOVEMENTS";
export const POST_SUPPLY_CONSULT_MOVEMENTS = "POST_SUPPLY_CONSULT_MOVEMENTS";

export const SUCCESS_GET_SUPPLY_PROVIDERS = "SUCCESS_GET_SUPPLY_PROVIDERS";
export const GET_SUPPLY_PROVIDERS = "GET_SUPPLY_PROVIDERS";

export const SUCCESS_POST_SUPPLY_REGISTER_MOVEMENT = "SUCCESS_POST_SUPPLY_REGISTER_MOVEMENT";
export const POST_SUPPLY_REGISTER_MOVEMENT = "POST_SUPPLY_REGISTER_MOVEMENT";

/** Alta de ítem en catálogo de insumos (POST `/insumo`, body tipo INSUMO). */
export const SUCCESS_POST_SUPPLY_CREATE = "SUCCESS_POST_SUPPLY_CREATE";
export const POST_SUPPLY_CREATE = "POST_SUPPLY_CREATE";

export const ERROR_SUPPLY = "ERROR_SUPPLY";
export const CLEAR_SUPPLY = "CLEAR_SUPPLY";
/** Limpia resultados de edición/baja de insumo en coordinación sin vaciar catálogo ni movimientos. */
export const CLEAR_SUPPLY_WRITES = "CLEAR_SUPPLY_WRITES";

export const SUCCESS_GET_SUPPLY_BY_ID = "SUCCESS_GET_SUPPLY_BY_ID";
export const GET_SUPPLY_BY_ID = "GET_SUPPLY_BY_ID";
export const SUCCESS_PUT_SUPPLY_BY_ID = "SUCCESS_PUT_SUPPLY_BY_ID";
export const PUT_SUPPLY_BY_ID = "PUT_SUPPLY_BY_ID";
export const SUCCESS_POST_SUPPLY_DELETE = "SUCCESS_POST_SUPPLY_DELETE";
export const POST_SUPPLY_DELETE = "POST_SUPPLY_DELETE";
//#endregion

//#region - ASSIGNMENT EXTRA
export const SUCCESS_PUT_ASSIGNMENT_BY_ID = "SUCCESS_PUT_ASSIGNMENT_BY_ID";
export const PUT_ASSIGNMENT_BY_ID = "PUT_ASSIGNMENT_BY_ID";
export const SUCCESS_DELETE_ASSIGNMENT_BY_ID = "SUCCESS_DELETE_ASSIGNMENT_BY_ID";
export const DELETE_ASSIGNMENT_BY_ID = "DELETE_ASSIGNMENT_BY_ID";
export const SUCCESS_POST_RESET_ABRAZOS_COLGADOS = "SUCCESS_POST_RESET_ABRAZOS_COLGADOS";
export const POST_RESET_ABRAZOS_COLGADOS = "POST_RESET_ABRAZOS_COLGADOS";
//#endregion

//#region - ASISTENCIA EXTRA
export const SUCCESS_GET_ASSISTANCE_REPORTE = "SUCCESS_GET_ASSISTANCE_REPORTE";
export const GET_ASSISTANCE_REPORTE = "GET_ASSISTANCE_REPORTE";
export const SUCCESS_POST_ASSISTANCE_DELETE = "SUCCESS_POST_ASSISTANCE_DELETE";
export const POST_ASSISTANCE_DELETE = "POST_ASSISTANCE_DELETE";

export const GET_ASSISTANCE_ALL = "GET_ASSISTANCE_ALL";
export const SUCCESS_GET_ASSISTANCE_ALL = "SUCCESS_GET_ASSISTANCE_ALL";
//#endregion

//#region - BABY EXTRA
export const SUCCESS_GET_BABY_BY_DNI = "SUCCESS_GET_BABY_BY_DNI";
export const GET_BABY_BY_DNI = "GET_BABY_BY_DNI";
export const SUCCESS_POST_BABY_DELETE = "SUCCESS_POST_BABY_DELETE";
export const POST_BABY_DELETE = "POST_BABY_DELETE";
export const GET_BABY_WEIGHT_EVOLUTION = "GET_BABY_WEIGHT_EVOLUTION";
export const SUCCESS_GET_BABY_WEIGHT_EVOLUTION = "SUCCESS_GET_BABY_WEIGHT_EVOLUTION";
export const GET_BABY_PERMANENCIA = "GET_BABY_PERMANENCIA";
export const SUCCESS_GET_BABY_PERMANENCIA = "SUCCESS_GET_BABY_PERMANENCIA";
//#endregion

//#region - MOTHER EXTRA
export const SUCCESS_POST_MOTHER_DELETE = "SUCCESS_POST_MOTHER_DELETE";
export const POST_MOTHER_DELETE = "POST_MOTHER_DELETE";
//#endregion

//#region - VOLUNTEER EXTRA
export const SUCCESS_POST_VOLUNTEER_DELETE = "SUCCESS_POST_VOLUNTEER_DELETE";
export const POST_VOLUNTEER_DELETE = "POST_VOLUNTEER_DELETE";
//#endregion

//#region - USER ADMIN
export const SUCCESS_POST_USUARIO = "SUCCESS_POST_USUARIO";
export const POST_USUARIO = "POST_USUARIO";
export const SUCCESS_GET_USUARIO_BY_ID = "SUCCESS_GET_USUARIO_BY_ID";
export const GET_USUARIO_BY_ID = "GET_USUARIO_BY_ID";
export const SUCCESS_PUT_USUARIO = "SUCCESS_PUT_USUARIO";
export const PUT_USUARIO = "PUT_USUARIO";
export const SUCCESS_POST_USUARIO_DELETE = "SUCCESS_POST_USUARIO_DELETE";
export const POST_USUARIO_DELETE = "POST_USUARIO_DELETE";
export const ERROR_USER = "ERROR_USER";
export const CLEAR_USER_ADMIN = "CLEAR_USER_ADMIN";
//#endregion

//#region - HORARIO
export const SUCCESS_GET_HORARIO_DIAS = "SUCCESS_GET_HORARIO_DIAS";
export const GET_HORARIO_DIAS = "GET_HORARIO_DIAS";
export const SUCCESS_POST_HORARIO = "SUCCESS_POST_HORARIO";
export const POST_HORARIO = "POST_HORARIO";
export const PUT_HORARIO = "PUT_HORARIO";
export const SUCCESS_PUT_HORARIO = "SUCCESS_PUT_HORARIO";
export const ERROR_HORARIO = "ERROR_HORARIO";
export const CLEAR_HORARIO = "CLEAR_HORARIO";
export const CLEAR_HORARIO_WRITES = "CLEAR_HORARIO_WRITES";
//#endregion

//#region - TAREA
export const GET_TAREAS = "GET_TAREAS";
export const SUCCESS_GET_TAREAS = "SUCCESS_GET_TAREAS";
export const GET_TAREAS_DISPONIBLES = "GET_TAREAS_DISPONIBLES";
export const SUCCESS_GET_TAREAS_DISPONIBLES = "SUCCESS_GET_TAREAS_DISPONIBLES";
export const GET_TAREA_BY_ID = "GET_TAREA_BY_ID";
export const SUCCESS_GET_TAREA_BY_ID = "SUCCESS_GET_TAREA_BY_ID";
export const POST_TAREA = "POST_TAREA";
export const SUCCESS_POST_TAREA = "SUCCESS_POST_TAREA";
export const PUT_TAREA = "PUT_TAREA";
export const SUCCESS_PUT_TAREA = "SUCCESS_PUT_TAREA";
export const POST_TAREA_DELETE = "POST_TAREA_DELETE";
export const SUCCESS_POST_TAREA_DELETE = "SUCCESS_POST_TAREA_DELETE";
export const ERROR_TAREA = "ERROR_TAREA";
export const CLEAR_TAREA_WRITES = "CLEAR_TAREA_WRITES";
//#endregion

//#region - VISITA
export const GET_VISITAS = "GET_VISITAS";
export const SUCCESS_GET_VISITAS = "SUCCESS_GET_VISITAS";
export const GET_VISITAS_BY_BEBE = "GET_VISITAS_BY_BEBE";
export const SUCCESS_GET_VISITAS_BY_BEBE = "SUCCESS_GET_VISITAS_BY_BEBE";
export const GET_VISITA_BY_ID = "GET_VISITA_BY_ID";
export const SUCCESS_GET_VISITA_BY_ID = "SUCCESS_GET_VISITA_BY_ID";
export const POST_VISITA = "POST_VISITA";
export const SUCCESS_POST_VISITA = "SUCCESS_POST_VISITA";
export const PUT_VISITA = "PUT_VISITA";
export const SUCCESS_PUT_VISITA = "SUCCESS_PUT_VISITA";
export const POST_VISITA_DELETE = "POST_VISITA_DELETE";
export const SUCCESS_POST_VISITA_DELETE = "SUCCESS_POST_VISITA_DELETE";
export const ERROR_VISITA = "ERROR_VISITA";
export const CLEAR_VISITA_WRITES = "CLEAR_VISITA_WRITES";
//#endregion

//#region - PROVEEDOR
export const GET_PROVEEDORES_ALL = "GET_PROVEEDORES_ALL";
export const SUCCESS_GET_PROVEEDORES_ALL = "SUCCESS_GET_PROVEEDORES_ALL";
export const POST_PROVEEDOR = "POST_PROVEEDOR";
export const SUCCESS_POST_PROVEEDOR = "SUCCESS_POST_PROVEEDOR";
export const PUT_PROVEEDOR = "PUT_PROVEEDOR";
export const SUCCESS_PUT_PROVEEDOR = "SUCCESS_PUT_PROVEEDOR";
export const POST_PROVEEDOR_DELETE = "POST_PROVEEDOR_DELETE";
export const SUCCESS_POST_PROVEEDOR_DELETE = "SUCCESS_POST_PROVEEDOR_DELETE";
export const ERROR_PROVEEDOR = "ERROR_PROVEEDOR";
export const CLEAR_PROVEEDOR_WRITES = "CLEAR_PROVEEDOR_WRITES";
//#endregion

//#region - SALA
export const GET_SALAS_ALL = "GET_SALAS_ALL";
export const SUCCESS_GET_SALAS_ALL = "SUCCESS_GET_SALAS_ALL";
export const POST_SALA = "POST_SALA";
export const SUCCESS_POST_SALA = "SUCCESS_POST_SALA";
export const PUT_SALA = "PUT_SALA";
export const SUCCESS_PUT_SALA = "SUCCESS_PUT_SALA";
export const POST_SALA_DELETE = "POST_SALA_DELETE";
export const SUCCESS_POST_SALA_DELETE = "SUCCESS_POST_SALA_DELETE";
export const ERROR_SALA = "ERROR_SALA";
export const CLEAR_SALA_WRITES = "CLEAR_SALA_WRITES";
//#endregion

//#region - USUARIO EXTRA
export const GET_USUARIOS = "GET_USUARIOS";
export const SUCCESS_GET_USUARIOS = "SUCCESS_GET_USUARIOS";
export const GET_VOLUNTARIAS_SIN_USUARIO = "GET_VOLUNTARIAS_SIN_USUARIO";
export const SUCCESS_GET_VOLUNTARIAS_SIN_USUARIO = "SUCCESS_GET_VOLUNTARIAS_SIN_USUARIO";
export const PUT_USUARIO_CONTRASENA = "PUT_USUARIO_CONTRASENA";
export const SUCCESS_PUT_USUARIO_CONTRASENA = "SUCCESS_PUT_USUARIO_CONTRASENA";
//#endregion

// ── Dashboard (coordinación del día y estadísticas del backend) ──
export const GET_COORDINACION_HOY = "GET_COORDINACION_HOY";
export const SUCCESS_GET_COORDINACION_HOY = "SUCCESS_GET_COORDINACION_HOY";
export const GET_COBERTURA_HOY = "GET_COBERTURA_HOY";
export const SUCCESS_GET_COBERTURA_HOY = "SUCCESS_GET_COBERTURA_HOY";
export const GET_BEBES_POR_SALA = "GET_BEBES_POR_SALA";
export const SUCCESS_GET_BEBES_POR_SALA = "SUCCESS_GET_BEBES_POR_SALA";
export const GET_BEBES_POR_ESTADO = "GET_BEBES_POR_ESTADO";
export const SUCCESS_GET_BEBES_POR_ESTADO = "SUCCESS_GET_BEBES_POR_ESTADO";
export const GET_BEBES_RANGO_EDADES = "GET_BEBES_RANGO_EDADES";
export const SUCCESS_GET_BEBES_RANGO_EDADES = "SUCCESS_GET_BEBES_RANGO_EDADES";
export const GET_RANKING_VOLUNTARIAS = "GET_RANKING_VOLUNTARIAS";
export const SUCCESS_GET_RANKING_VOLUNTARIAS = "SUCCESS_GET_RANKING_VOLUNTARIAS";
export const GET_DURACION_ABRAZOS = "GET_DURACION_ABRAZOS";
export const SUCCESS_GET_DURACION_ABRAZOS = "SUCCESS_GET_DURACION_ABRAZOS";
export const ERROR_DASHBOARD = "ERROR_DASHBOARD";
export const CLEAR_DASHBOARD = "CLEAR_DASHBOARD";

// ── Asistente IA ──
export const GET_ASISTENTE_ESTADO = "GET_ASISTENTE_ESTADO";
export const SUCCESS_GET_ASISTENTE_ESTADO = "SUCCESS_GET_ASISTENTE_ESTADO";
export const POST_ASISTENTE_PREGUNTA = "POST_ASISTENTE_PREGUNTA";
export const SUCCESS_POST_ASISTENTE_PREGUNTA = "SUCCESS_POST_ASISTENTE_PREGUNTA";
export const ERROR_ASISTENTE = "ERROR_ASISTENTE";
export const CLEAR_ASISTENTE = "CLEAR_ASISTENTE";
